# Generated by Django 5.0.6 on 2024-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='password',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
