# Generated by Django 5.0.6 on 2024-07-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_businessregistration_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='password',
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='state',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='website',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualregistration',
            name='experience',
            field=models.CharField(max_length=255),
        ),
    ]
