# Generated by Django 5.0.6 on 2024-07-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_businessregistration_requiredexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='businessregistration',
            name='skills',
        ),
    ]
