# Generated by Django 5.0.6 on 2024-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_remove_businessregistration_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
