# Generated by Django 5.0.6 on 2024-07-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_businessregistration_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistration',
            name='industry',
            field=models.CharField(default='IT-Software, Software Services', max_length=255),
        ),
    ]
