# Generated by Django 5.0.6 on 2024-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_businessregistration_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistration',
            name='industry',
            field=models.CharField(blank=True, default='IT-Software, Software Services', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='name',
            field=models.CharField(blank=True, default='software developer', max_length=255),
        ),
    ]
