# Generated by Django 5.0.6 on 2024-08-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_businessregistration_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistration',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
