# Generated by Django 5.0.6 on 2024-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_businessregistration_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
