# Generated by Django 5.0.6 on 2024-08-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_businessregistration_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='password',
        ),
    ]
