# Generated by Django 5.0.6 on 2024-08-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_remove_businessregistration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
