# Generated by Django 5.0.6 on 2024-08-22 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_company_alter_jobposting_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='registration.businessregistration'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
