# Generated by Django 5.0.6 on 2024-08-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_jobposting_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
