# Generated by Django 5.0.6 on 2024-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_jobposting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
