# Generated by Django 5.0.6 on 2024-09-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_businessregistration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='user',
        ),
    ]
